spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teste@gmail.com
    password:                        # Substitua pela senha ou app password
    protocol: smtp                   # Corrigido de "smat" para "smtp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enabled: true

envio:
  mail:
    remetente: 'email-pra-quem-quer-envia-@gmail.com'
    nomeRemetente: 'Target Car Rastreamento'  # Corrigida a identação

server:
  port: 8082
